// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoF36FCvgYISxtPC6OgXn4TSfV0yK03XY',
    appId: '1:296423355061:web:dee1b1451424a5322684fc',
    messagingSenderId: '296423355061',
    projectId: 'weed-lovers-chess-kitchen',
    authDomain: 'weed-lovers-chess-kitchen.firebaseapp.com',
    storageBucket: 'weed-lovers-chess-kitchen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhvVJKyOYTVbZBm-0zmOIrYCFPMQhP9fU',
    appId: '1:296423355061:android:387acf88e16763492684fc',
    messagingSenderId: '296423355061',
    projectId: 'weed-lovers-chess-kitchen',
    storageBucket: 'weed-lovers-chess-kitchen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKNfWOBVoQhyQrutQdWlNpHJBfl9-1WSY',
    appId: '1:296423355061:ios:c0d08596117206942684fc',
    messagingSenderId: '296423355061',
    projectId: 'weed-lovers-chess-kitchen',
    storageBucket: 'weed-lovers-chess-kitchen.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKNfWOBVoQhyQrutQdWlNpHJBfl9-1WSY',
    appId: '1:296423355061:ios:c0d08596117206942684fc',
    messagingSenderId: '296423355061',
    projectId: 'weed-lovers-chess-kitchen',
    storageBucket: 'weed-lovers-chess-kitchen.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );
}
